---
- name: "create app directory"
  file:
    path: /home/ubuntu/backend
    state: directory
    mode: 0755

- name: copy files to backend
  become: yes
  copy: 
    src: artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz

- name: unzip backend directory
  become: yes
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz

- name: "Extract Files and starting the appln"
  become: yes
  shell: |
    cd /home/ubuntu/backend/
    npm install
    pm2 stop default
    pm2 start npm -- start
