---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  become_method: sudo
  become_user: root  
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

      environment:      
      - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
      - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
      - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
      - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_HOST')}}"
      - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
      - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
      - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
      - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_PORT')}}"
      - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
  
    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

    - setup:
  roles:
    - deploy
